/**
    @mainpage Курсовой проект: Шахматы 3
    Тема проекта: "Компьютерный вариант игры шахматы с возможностью играть двум игрокам в режиме «горячего стула»"
    По дисциплине: "Проектирование программного обеспечения"
    @author Шабанов М., Тюканов В., Листопад В.
    @date 23-14-2023
\par Использует классы:
- @ref CastleKingSide
- @ref CastleQueenSide
- @ref Move
- @ref NormalMove
- @ref PawnPromiton
- @ref Bishop
- @ref King
- @ref Knight
- @ref Pawn
- @ref Piece
- @ref Queen
- @ref Rook
- @ref Board
- @ref Direction
- @ref GameState
- @ref Player
- @ref Position
- @ref Result
- @ref GameOverMenu
- @ref Images
- @ref MainWindow
- @ref Option
- @ref PromotionMenu
- @ref Reference
\per Содержит перечисления:
- @ref MoveType
- @ref PieceType
- @ref EndReason
\par Содержит файлы:
- @ref CastleKingSide.cs
- @ref CastleQueenSide.cs
- @ref Move.cs
- @ref NormalMove.cs
- @ref PawnPromiton.cs
- @ref Bishop.cs
- @ref King.cs
- @ref Knight.cs
- @ref Pawn.cs
- @ref Piece.cs
- @ref Queen.cs
- @ref Rook.cs
- @ref Board.cs
- @ref Direction.cs
- @ref EndReason.cs
- @ref GameState.cs
- @ref MoveType.cs
- @ref PieceType.cs
- @ref Player.cs
- @ref Position.cs
- @ref Result.cs
- @ref GameOverMenu.xaml.cs
- @ref Images.cs
- @ref MainWindow.xaml.cs
- @ref Option.cs
- @ref PromotionMenu.xaml.cs
- @ref Reference.xaml.cs
- @ref Assets/Ask.png
- @ref Assets/BishopW.png
- @ref Assets/BishopB.png
- @ref Assets/Board.png
- @ref Assets/Exit.png
- @ref Assets/Icon.png
- @ref Assets/KingB.png
- @ref Assets/KingW.png
- @ref Assets/KnightB.png
- @ref Assets/KnightW.png
- @ref Assets/PawnB.png
- @ref Assets/PawnW.png
- @ref Assets/QueenB.png
- @ref Assets/QueenW.png
- @ref Assets/RookB.png
- @ref Assets/RookW.png
*/